apiVersion: v1
kind: Pod
metadata:
  name: pod-libdontdie-test
spec:
  containers:
    - name: hello-container
      image: gcr.io/sandbox-testing-215308/libdontdie:test
      imagePullPolicy: Always
      env:
       - name: LD_PRELOAD
         value: "/usr/lib/libdontdie.so"
       - name: DD_TCP_KEEPALIVE_PROBES
         value: "5"
       - name: DD_TCP_KEEPALIVE_TIME
         value: "60"
       - name: DD_TCP_KEEPALIVE_INTVL
         value: "60"
       - name: DD_EVAL_ENVIRONMENT_ONCE
         value: "1"
  restartPolicy: OnFailure

# cd resources
# kubectl config current-context
# kubectl apply -f pod.yaml
# kubectl get pod/pod-demo-<your name>
# kubectl describe pod/pod-demo-<your name>
# kubectl logs pod-demo-<your name>
# kubectl delete pod pod-demo-<your name>
# tcpdump -i eth0 dst 35.226.98.122